#ifndef APPCONST_H
#define APPCONST_H
	#define STR_MAX 256
	#define ITEM_WIDTH 150
	#define ITEM_HEIGHT 40
	#define ITEM_INFO_WIDTH 1000
	#define ITEM_INFO_HEIGHT 60
	#define ITEM_INFO_INITIAL_HEIGTH 15
#endif