#ifndef ICONLABELIDS_H
#define ICONLABELIDS_H
#define BIOS_ICON_LABEL 60
#define OS_ICON_LABEL 61
#define CPU_ICON_LABEL 62
#define RAM_ICON_LABEL 63
#define MB_ICON_LABEL 64
#define VIDEO_ICON_LABEL 65
#define DISPLAY_ICON_LABEL 66
#define STORAGE_ICON_LABEL 67
#define OPTICAL_ICON_LABEL 68
#define NETWORK_ICON_LABEL 69
#define AUDIO_ICON_LABEL  70
#define UPTIME_ICON_LABEL 71 
#endif