#ifndef APPCONST_H
	#define APPCONST_H
	#define STR_MAX 256
	#define ITEM_WIDTH 200
	#define ITEM_HEIGHT 40
	#define ITEM_BOTTOM_MARGIN 5
	#define ITEM_INFO_WIDTH 1000
	#define ITEM_INFO_HEIGHT 60
	#define ITEM_INFO_INITIAL_HEIGTH 22
	#define ITEM_ICON_SIZE 16
	#define ITEM_UTIL_ICON_RENDER_SIZE_WIDTH 12
	#define ITEM_UTIL_ICON_RENDER_SIZE_HEIGHT 14
	#define MOUSE_WHEEL_SCROLL 120
	#define ITEM_INFO_Y_OFFSET 16
	#define ITEM_GENERIC_SMALL_OFFSET 20

	#define ITEM_HI_DPI_CPU_UTIL_OFFSET 20
	#define ITEM_NON_HI_DPI_CPU_UTIL_OFFSET 16

	#define ITEM_WIDTH_HI_DPI 200
	#define ITEM_WIDTH_NON_HI_DPI 160

	#define ITEM_INFO_HEIGHT_NON_HI_DPI 60
	#define ITEM_INFO_HEIGHT_HI_DPI 60

	#define ITEM_INFO_BOTTOM_MARGIN 10

	#define ADJUSTED_BOX_ITEM_HEIGHT_BOTTOM_MARGIN_HI_DPI 10
	#define ADJUSTED_BOX_ITEM_HEIGHT_BOTTOM_MARGIN_NON_HI_DPI 0 
#endif