#ifndef ITEMIDS_H
	#define ITEMIDS_H
	#define SNAPSHOT_LABEL -1
	#define BIOS_LABEL 0
	#define OS_LABEL 1
	#define CPU_LABEL 2
	#define MB_LABEL 3
	#define RAM_LABEL 4
	#define GPU_LABEL 5
	#define MONITOR_LABEL 6
	#define STORAGE_LABEL 7
	#define OPTICAL_LABEL 8
	#define NETWORK_LABEL 9
	#define AUDIO_LABEL 10
	#define UPTIME_LABEL 11
	#define BIOS_INFO 12
	#define OS_INFO 13
	#define CPU_INFO 14
	#define MB_INFO 15
	#define RAM_INFO 16
	#define GPU_INFO 17
	#define MONITOR_INFO 18
	#define STORAGE_INFO 19	
	#define OPTICAL_INFO 20
	#define NETWORK_INFO 21
	#define AUDIO_INFO 22
	#define UPTIME_INFO 23
	#define END_INFO 24

	#define AUX_IP_TOGGLE 720
	#define AUX_CPU_INFO_TOTAL_UTILIZATION_PERCENTAGE_ICON 820
	#define AUX_CPU_INFO_TOTAL_UTILIZATION_PERCENTAGE_STRING 920



	#define INFO_ID_OFFSET 12
	#define ICON_ID_OFFSET 60
	#define IDC_SETTINGS_TABAREA 70
	#define TAB_CONTENT_WRAPPER_OFFSET 5000

	#define TAB_CONTENT_CHKBOX_CPU_USAGE 0x9C4A
	#define TAB_CONTENT_CHKBOX_HDD_TEMP 0x9C54
	#define TAB_CONTENT_CHKBOX_SCRCAP_CLIENT_ONLY 0x9C5E
	#define TAB_CONTENT_CHKBOX_RMB_LAST_WIN_POS 0x9C68 //arr in globalvars
	#define TAB_CONTENT_CHKBOX_HIDE_IP_ADDR 0x9C72

	#define TAB_ÑONTENT_HTML_EXPORT_HEADER 8000
	#define TAB_ÑONTENT_HTML_EXPORT_INFO 9000
	#define TAB_ÑONTENT_HTML_EXPORT_HEADER_BG_COLOR 10000
	#define TAB_ÑONTENT_HTML_EXPORT_HEADER_FG_COLOR 11000
	#define TAB_ÑONTENT_HTML_EXPORT_INFO_BG_COLOR 12000
	#define TAB_ÑONTENT_HTML_EXPORT_INFO_FG_COLOR 13000

	#define IDC_SETTINGS_CONTROL_BTN_SAVE 14000
	#define IDC_SETTINGS_CONTROL_BTN_CANCEL 15000
	#define IDC_SETTINGS_CONTROL_BTN_RESET 16000
	#define TAB_CONTENT_UAC_ICON_STATIC 16100
#endif